# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Creds
      run: "echo 'Data ${{ secrets.GITHUB_ACTOR }} ${{ secrets.GITHUB_TOKEN }}'"
    - name: Set up Maven Settings for deploy
      uses: s4u/maven-settings-action@v2.6.0
      with:
        servers: '[{"id": "github/dishantkamble", "username": "${{ secrets.GITHUB_ACTOR }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
    - name: Build with Maven
      run: mvn -B package --file pom.xml install -Dtoken=$GITHUB_TOKEN
